name: 📖 User Story
description: Propose a new feature or improvement in the form of a Job Story
title: "📖: [Short Summary]"
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: "**A user story is a** short, simple description of a feature told from the perspective of the person who desires the new capability, usually a user or customer of the system"
  - type: textarea
    attributes:
      label: User Story
      value: "As a [type of user], I want [some goal] so [some reason]."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Acceptance Criteria
      value: "- [ ] {Acceptance criterion 1}"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## ✅ Sprint Ready Checklist

        - [ ] The user story is understood by everyone.
        - [ ] The acceptance criteria are defined and measurable
